# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_id', models.CharField(max_length=100)),
                ('cache', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
