# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aiml_kernel', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='requestcache',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatter.UserCache'),
        ),
    ]
