# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0003_auto_20170113_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcache',
            name='cache_id',
            field=models.CharField(max_length=100),
        ),
    ]
