# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0004_auto_20170113_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercache',
            name='aiml_kernel',
            field=models.CharField(max_length=102400),
        ),
    ]
